query GetCheckoutSession($orderId: ID!) {
  checkoutSession: getCheckout(orderId: $orderId) {
    orderId
    clientSecret
    orderId
    status
    breakdown {
      startDate
      discount
      total
    }
  }
}
