query ValidateGiftVoucher($voucher: String!) {
  validateGiftVoucher(voucher: $voucher) {
    valid
    isLegacyVoucher
  }
}

mutation RedeemGiftVoucher($voucher: String!) {
  redeemGiftVoucher(voucherCode: $voucher) {
    aboType
    starting
  }
}
