query ValidateGiftVoucher($voucher: String!) {
  validateGiftVoucher(voucherCode: $voucher) {
    valid
    isLegacyVoucher
    company
  }
}

mutation RedeemGiftVoucher($voucher: String!) {
  redeemGiftVoucher(voucherCode: $voucher) {
    aboType
    starting
  }
}
