query Me {
  me {
    id
    portrait
    name
    firstName
    lastName
    email

    address {
      name
      line1
      line2
      postalCode
      city
      country
    }

    activeMembership {
      id
      type {
        name
      }
      active
      endDate
    }

    activeMagazineSubscription {
      id
      type
      company
      status
      currentPeriodStart
      currentPeriodEnd
      renewsAtPrice
      cancelAt
    }
  }
}
