query OfferCard($offerId: ID!, $promoCode: String) {
  offer: getOffer(offerId: $offerId, promoCode: $promoCode) {
    id
    name
    availability

    price {
      amount
      currency
      recurring {
        interval
      }
    }

    discount {
      amountOff
      duration
    }
  }
}

query OfferCheckout($offerId: ID!, $promoCode: String) {
  offer: getOffer(offerId: $offerId, promoCode: $promoCode) {
    id
    company
    name
    requiresLogin
    requiresAddress
    availability

    # __typename needs to be specified explicitly
    __typename
    ... on SubscriptionOffer {
      startDate
    }

    price {
      amount
      currency
      recurring {
        interval
        intervalCount
      }
    }

    discount {
      name
      amountOff
      duration # forever | repeating | once
      durationInMonths # only relevant when duration is "repeating"
    }

    suggestedDonations

    discountOptions {
      id
      name
      amountOff
      duration
      durationInMonths
      currency
    }
  }
}
