query OfferCard($offerId: ID!) {
  offer: getOffer(offerId: $offerId) {
    id
    name

    price {
      amount
      currency
      recurring {
        interval
      }
    }

    discount {
      amountOff
      duration
    }
  }
}

query OfferCheckout($offerId: ID!, $promoCode: String) {
  offer: getOffer(offerId: $offerId, promoCode: $promoCode) {
    id
    company
    name
    requiresLogin
    requiresAddress

    price {
      amount
      currency
      recurring {
        interval
        intervalCount
      }
    }

    discount {
      name
      amountOff
      duration # forever | repeating | once
      # durationInMonths # only relevant when duration is "repeating"
    }

    suggestedDonations

    discountOptions {
      id
      name
      amountOff
      duration
      durationInMonths
      currency
    }
  }
}
