query OfferCard($offerId: ID!) {
  offer: getOffer(offerId: $offerId) {
    id
    name

    price {
      amount
      currency
      recurring {
        interval
      }
    }

    customPrice {
      min
    }

    discount {
      name
      amountOff
    }
  }
}

query OfferCheckout($offerId: ID!, $promoCode: String) {
  offer: getOffer(offerId: $offerId, promoCode: $promoCode) {
    id
    company
    name
    requiresLogin
    requiresAddress

    donationOptions {
      id
      price {
        amount
        currency
        recurring {
          interval
          intervalCount
        }
      }
    }

    price {
      amount
      currency
      recurring {
        interval
        intervalCount
      }
    }

    discountOptions {
      id
      name
      amountOff
      duration
      durationInMonths
      currency
    }

    # customPrice {
    #   min
    #   max
    #   step
    # }

    discount {
      name
      amountOff
      duration # forever | repeating | once
      # durationInMonths # only relevant when duration is "repeating"
    }
  }
}
